# Unless filling for special features, all features should fill for previous forks (starting from Frontier) too
stable:
  evm-type: stable
  fill-params: --until=Prague --fill-static-tests --ignore=tests/static/state_tests/stQuadraticComplexityTest

develop:
  evm-type: develop 
  fill-params: --until=BPO4 --fill-static-tests --ignore=tests/static/state_tests/stQuadraticComplexityTest

benchmark:
  evm-type: benchmark
  fill-params: --fork=Prague --gas-benchmark-values 1,5,10,30,60,100,150 -m "benchmark and not state_test" ./tests/benchmark

benchmark_develop:
  evm-type: benchmark
  fill-params: --fork=Osaka --gas-benchmark-values 1,5,10,30,60,100,150 -m "benchmark and not state_test" ./tests/benchmark
  feature_only: true

benchmark_fast:
  evm-type: benchmark
  fill-params: --fork=Prague --gas-benchmark-values 100 -m "benchmark and not state_test" ./tests/benchmark
  feature_only: true

bal:
  evm-type: develop
  # TODO: Turn on block rlp limit tests after making filling them more flexible.
  fill-params: --fork=Amsterdam -k "not eip7934" --fill-static-tests
  feature_only: true
